import { main } from '.'

// const fileContent = `BALANCE MC1 600
// BALANCE MC2 500
// BALANCE MC3 50
// BALANCE MC4 50
// BALANCE MC5 200
// CHECK_IN MC1 ADULT CENTRAL
// CHECK_IN MC2 SENIOR_CITIZEN CENTRAL
// CHECK_IN MC1 ADULT AIRPORT
// CHECK_IN MC3 KID AIRPORT
// CHECK_IN MC4 ADULT AIRPORT
// CHECK_IN MC5 KID AIRPORT
// PRINT_SUMMARY`

const fileContent = `BALANCE MC1 400
BALANCE MC2 100 
BALANCE MC3 50 
BALANCE MC4 50
CHECK_IN MC1 SENIOR_CITIZEN AIRPORT 
CHECK_IN MC2 KID AIRPORT 
CHECK_IN MC3 ADULT CENTRAL 
CHECK_IN MC1 SENIOR_CITIZEN CENTRAL 
CHECK_IN MC3 ADULT AIRPORT 
CHECK_IN MC3 ADULT CENTRAL 
PRINT_SUMMARY`

fit('runs', () => {
  const output = main(fileContent)

  expect(output).toBe('fasdf')
})
