name: github pages

on:
  push:
    branches:
      - master # Set a branch to deploy
  pull_request:

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-20.04
    # Set job outputs to values from filter step
    outputs:
      gmail-clone-app: ${{ steps.filter.outputs.gmail-clone-app }}
      web-dev-blog: ${{ steps.filter.outputs.web-dev-blog }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            gmail-clone-app:
              - 'apps/gmail-clone-app/**'
            web-dev-blog:
              - 'apps/web-dev-blog/**'
  deploy-web-dev-blog:
    needs: changes
    if: ${{ needs.changes.outputs.web-dev-blog == 'true' }}
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: apps/web-dev-blog
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: HUGO_ENV=production hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          personal_token: ${{ secrets.REPO_ACCESS }}
          external_repository: HarshRohila/harshrohila.github.io
          publish_branch: master
          publish_dir: ./apps/web-dev-blog/public
  deploy-gmail-clone-app:
    needs: changes
    if: ${{ needs.changes.outputs.gmail-clone-app == 'true' }}
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - uses: nrwl/nx-set-shas@v2
      - run: npm i
      - run: npx nx predeploy gmail-clone-app

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          personal_token: ${{ secrets.REPO_ACCESS }}
          external_repository: HarshRohila/gmail-clone
          publish_branch: gh-pages
          publish_dir: ./dist/apps/gmail-clone-app/www
